version: '3'

services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/demo

  postgres:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  db-data: